# Generated by Django 3.0.8 on 2020-08-01 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DistritoElectoral',
            fields=[
                ('codigo_electoral', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('provincia', models.CharField(max_length=10)),
                ('canton', models.CharField(max_length=26)),
                ('distrito', models.CharField(max_length=36)),
            ],
            options={
                'ordering': ['codigo_electoral'],
            },
        ),
        migrations.CreateModel(
            name='Elector',
            fields=[
                ('cedula', models.CharField(max_length=9, primary_key=True, serialize=False, unique=True)),
                ('codigo_electoral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electoral_roll.DistritoElectoral')),
                ('relleno', models.CharField(max_length=1)),
                ('fecha_caducidad', models.DateTimeField()),
                ('junta', models.CharField(max_length=5)),
                ('nombre', models.CharField(max_length=30)),
                ('primer_apellido', models.CharField(max_length=26)),
                ('segundo_apellido', models.CharField(max_length=26)),
            ],
            options={
                'ordering': ['codigo_electoral'],
            },
        ),
        migrations.AddIndex(
            model_name='distritoelectoral',
            index=models.Index(fields=['codigo_electoral'], name='electoral_r_codigo__4dc74b_idx'),
        ),
        migrations.AddIndex(
            model_name='elector',
            index=models.Index(fields=['cedula', 'codigo_electoral'], name='electoral_r_cedula_38140b_idx'),
        ),
    ]
