# Generated by Django 3.0.8 on 2020-08-05 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('electoral_roll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotantesPorCanton',
            fields=[
                ('codigo_canton', models.AutoField(primary_key=True, serialize=False)),
                ('canton', models.CharField(max_length=26)),
                ('total_votantes', models.IntegerField()),
                ('total_votantes_hombres', models.IntegerField()),
                ('total_votantes_mujeres', models.IntegerField()),
            ],
            options={
                'ordering': ['codigo_provincia'],
            },
        ),
        migrations.CreateModel(
            name='VotantesPorProvincia',
            fields=[
                ('codigo_provincia', models.AutoField(primary_key=True, serialize=False)),
                ('provincia', models.CharField(max_length=10, unique=True)),
                ('total_votantes', models.IntegerField()),
                ('total_votantes_hombres', models.IntegerField()),
                ('total_votantes_mujeres', models.IntegerField()),
            ],
            options={
                'ordering': ['codigo_provincia'],
            },
        ),
        migrations.RemoveIndex(
            model_name='elector',
            name='electoral_r_cedula_38140b_idx',
        ),
       
        migrations.AddIndex(
            model_name='votantesporprovincia',
            index=models.Index(fields=['codigo_provincia'], name='electoral_r_codigo__881d3d_idx'),
        ),
        migrations.AddIndex(
            model_name='votantesporprovincia',
            index=models.Index(fields=['provincia'], name='electoral_r_provinc_328a38_idx'),
        ),
        migrations.AddField(
            model_name='votantesporcanton',
            name='codigo_provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electoral_roll.VotantesPorProvincia'),
        ),
        migrations.AddIndex(
            model_name='votantesporcanton',
            index=models.Index(fields=['codigo_canton'], name='electoral_r_codigo__f87037_idx'),
        ),
        migrations.AddIndex(
            model_name='votantesporcanton',
            index=models.Index(fields=['canton'], name='electoral_r_canton_499f18_idx'),
        ),
    ]
