# Generated by Django 3.0.8 on 2020-08-06 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('electoral_roll', '0002_auto_20200804_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotantesPorDistrito',
            fields=[
                ('codigo_distrito', models.AutoField(primary_key=True, serialize=False)),
                ('distrito', models.CharField(max_length=36)),
                ('total_votantes', models.IntegerField()),
                ('total_votantes_hombres', models.IntegerField()),
                ('total_votantes_mujeres', models.IntegerField()),
            ],
            options={
                'ordering': ['codigo_canton'],
            },
        ),
        
        migrations.AddIndex(
            model_name='votantesporcanton',
            index=models.Index(fields=['codigo_provincia'], name='electoral_r_codigo__432239_idx'),
        ),
        migrations.AddField(
            model_name='votantespordistrito',
            name='codigo_canton',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electoral_roll.VotantesPorCanton'),
        ),
        migrations.AddIndex(
            model_name='votantespordistrito',
            index=models.Index(fields=['codigo_canton'], name='electoral_r_codigo__c72b52_idx'),
        ),
    ]
