# Generated by Django 3.0.8 on 2020-08-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electoral_roll', '0003_auto_20200805_2049'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='elector',
            index=models.Index(fields=['cedula'], name='electoral_r_cedula_f72449_idx'),
        ),
        migrations.AddIndex(
            model_name='elector',
            index=models.Index(fields=['nombre'], name='electoral_r_nombre_c88dda_idx'),
        ),
        migrations.AddIndex(
            model_name='elector',
            index=models.Index(fields=['primer_apellido'], name='electoral_r_primer__426955_idx'),
        ),
        migrations.AddIndex(
            model_name='elector',
            index=models.Index(fields=['segundo_apellido'], name='electoral_r_segundo_f19edc_idx'),
        ),
        migrations.AddIndex(
            model_name='elector',
            index=models.Index(fields=['fecha_caducidad'], name='electoral_r_fecha_c_ee20c8_idx'),
        ),
        migrations.AddIndex(
            model_name='elector',
            index=models.Index(fields=['codigo_electoral'], name='electoral_r_codigo__78191e_idx'),
        ),
    ]
