# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(db_index=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('remote_addr', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('req_method', models.CharField(blank=True, max_length=32, null=True)),
                ('req_path', models.TextField(blank=True, null=True)),
                ('req_headers_json', models.TextField(blank=True, null=True)),
                ('req_body', models.TextField(blank=True, null=True)),
                ('res_status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('res_reason_phrase', models.CharField(blank=True, max_length=128, null=True)),
                ('res_headers_json', models.TextField(blank=True, null=True)),
                ('res_body', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_regex', models.CharField(max_length=1024)),
                ('mask_chd', models.BooleanField(default=True, help_text='When enabled, all 3 or 4 digit CVV values are masked in the request body. Also masks all but last 4 characters for credit card numbers.')),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
