# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-08-07 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiretap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='interaction_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
