# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-04-07 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wiretap', '0002_message_interaction_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField(db_index=True)),
                ('mode', models.CharField(blank=True, choices=[('live', 'Live'), ('test', 'Test')], max_length=16, null=True)),
                ('test_request', models.BooleanField(default=False)),
                ('interaction_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('interaction_type', models.CharField(blank=True, choices=[('call', 'Call'), ('text', 'Text'), ('web', 'Web')], max_length=32, null=True)),
                ('client_reference_code', models.CharField(blank=True, max_length=128, null=True)),
                ('customer_id', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('processor_result', models.CharField(blank=True, choices=[('approved', 'Approved'), ('review', 'Held For Review'), ('error', 'Error'), ('declined', 'Declined')], db_index=True, max_length=32, null=True)),
                ('processor_transaction_id', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('processor_message', models.TextField(blank=True, null=True)),
                ('processor_request', models.TextField(blank=True, null=True)),
                ('processor_response', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('processor', models.CharField(blank=True, choices=[('authorize_net', 'Authorize.Net'), ('cybersource', 'Cybersource'), ('payrazr', 'Payrazr'), ('payrazr_rest', 'Payrazr REST'), ('paytrace', 'PayTrace'), ('trustcommerce', 'TrustCommerce'), ('usaepay', 'USAePay'), ('bluefin', 'Bluefin PayConex'), ('elavon_convergepay', 'Elavon Convergepay'), ('elavon_instamed', 'Elavon Instamed'), ('convenient_payments', 'Convenient Payments'), ('chase', 'Chase')], db_index=True, max_length=128, null=True)),
                ('transaction_type', models.CharField(blank=True, choices=[('authorize', 'Authorize'), ('capture', 'Capture'), ('sale', 'Sale'), ('void', 'Void'), ('refund', 'Refund')], db_index=True, max_length=128, null=True)),
                ('tender_type', models.CharField(blank=True, choices=[('credit_card', 'Credit Card'), ('ach', 'ACH / e-Check')], db_index=True, max_length=16, null=True)),
                ('amount', models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=10, null=True)),
                ('original_transaction_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('card_account_number', models.CharField(blank=True, db_index=True, max_length=4, null=True)),
                ('card_type', models.CharField(blank=True, choices=[('visa', 'Visa'), ('mastercard', 'MasterCard'), ('american_express', 'American Express'), ('discover', 'Discover'), ('jcb', 'JCB'), ('amex', 'Amex')], db_index=True, max_length=32, null=True)),
                ('ach_name_on_account', models.CharField(blank=True, max_length=256, null=True)),
                ('ach_account_number', models.CharField(blank=True, db_index=True, max_length=4, null=True)),
                ('ach_routing_number', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('ach_account_type', models.CharField(blank=True, choices=[('savings', 'Savings'), ('checking', 'Checking'), ('commercial', 'Commercial')], db_index=True, max_length=32, null=True)),
                ('ach_check_number', models.CharField(blank=True, max_length=8, null=True)),
                ('bill_to_first_name', models.CharField(blank=True, max_length=128, null=True)),
                ('bill_to_last_name', models.CharField(blank=True, max_length=128, null=True)),
                ('bill_to_company', models.CharField(blank=True, max_length=128, null=True)),
                ('bill_to_address', models.CharField(blank=True, max_length=128, null=True)),
                ('bill_to_city', models.CharField(blank=True, max_length=128, null=True)),
                ('bill_to_county', models.CharField(blank=True, max_length=128, null=True)),
                ('bill_to_state', models.CharField(blank=True, max_length=128, null=True)),
                ('bill_to_zip', models.CharField(blank=True, max_length=16, null=True)),
                ('bill_to_country', models.CharField(blank=True, max_length=128, null=True)),
                ('bill_to_phone', models.CharField(blank=True, max_length=32, null=True)),
                ('bill_to_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('ship_to_first_name', models.CharField(blank=True, max_length=128, null=True)),
                ('ship_to_last_name', models.CharField(blank=True, max_length=128, null=True)),
                ('ship_to_company', models.CharField(blank=True, max_length=128, null=True)),
                ('ship_to_address', models.CharField(blank=True, max_length=128, null=True)),
                ('ship_to_city', models.CharField(blank=True, max_length=128, null=True)),
                ('ship_to_county', models.CharField(blank=True, max_length=128, null=True)),
                ('ship_to_state', models.CharField(blank=True, max_length=128, null=True)),
                ('ship_to_zip', models.CharField(blank=True, max_length=16, null=True)),
                ('ship_to_country', models.CharField(blank=True, max_length=128, null=True)),
                ('ship_to_phone', models.CharField(blank=True, max_length=32, null=True)),
                ('ship_to_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=32, null=True)),
                ('message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='wiretap.Message')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['interaction_id', 'interaction_type'], name='payments_ap_interac_68712d_idx'),
        ),
    ]
