# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-21 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='processor',
            field=models.CharField(blank=True, choices=[('authorize_net', 'Authorize.Net'), ('cybersource', 'Cybersource'), ('payrazr', 'Payrazr'), ('payrazr_rest', 'Payrazr REST'), ('paytrace', 'PayTrace'), ('trustcommerce', 'TrustCommerce'), ('usaepay', 'USAePay'), ('bluefin', 'Bluefin PayConex'), ('elavon_convergepay', 'Elavon Convergepay'), ('elavon_instamed', 'Elavon Instamed'), ('convenient_payments', 'Convenient Payments'), ('chase', 'Chase'), ('stripe', 'Stripe')], db_index=True, max_length=128, null=True),
        ),
    ]
