# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-21 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments_api', '0002_auto_20201021_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
