# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-29 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments_api', '0005_auto_20201027_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='ach_account_type',
            field=models.CharField(blank=True, choices=[('savings', 'Savings'), ('checking', 'Checking'), ('commercial', 'Commercial'), ('individual', 'Individual'), ('company', 'Company'), ('corporate', 'Corporate')], db_index=True, max_length=32, null=True),
        ),
    ]
