version: '3'

services:
  # Database
  db:
    image: mysql:5.7
    volumes:
      - db_mydata:/var/lib/mysql
#    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: core_services_payments
      MYSQL_USER: user
      MYSQL_PASSWORD: user123
    networks:
      - newsite
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
#    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password 
    networks:
      - newsite

 
networks:
  newsite:
volumes:
  db_mydata:
