# Generated by Django 4.2.5 on 2023-10-02 01:09

from django.db import migrations
from books.models import Books, Author
import random


# Function to generate a random book name
def generate_book_name():
    # Lists of words and phrases for book titles
    prefixes = ["The", "A", "An", "My", "Your", "His", "Her"]
    nouns = [
        "Adventure",
        "Mystery",
        "Romance",
        "Fantasy",
        "Science Fiction",
        "Thriller",
        "Horror",
    ]
    adjectives = [
        "Dark",
        "Secret",
        "Enchanted",
        "Mysterious",
        "Epic",
        "Lost",
        "Forgotten",
    ]
    suffixes = [
        "Chronicles",
        "Quest",
        "Journey",
        "Legacy",
        "Curse",
        "Mystery",
        "Adventures",
    ]
    title = random.choice(prefixes) + " "
    if random.random() < 0.5:
        title += random.choice(adjectives) + " "
    title += random.choice(nouns)
    if random.random() < 0.3:
        title += ": " + random.choice(suffixes)
    return title


def add_books(apps, schema_editor):
    books = apps.get_model("books", "Books")
    # Generate and print random book names
    num_books = 100_000

    for _ in range(num_books):
        book_name = generate_book_name()
        random_number = random.randint(1, 3)
        author = Author.objects.get(id=random_number)
        book = Books(title=book_name, description="Book Description", author=author)
        book.save()


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(add_books, migrations.RunPython.noop),
    ]
